import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { ReactNode } from "react";

// 정적 import
import koMessages from '../../locales/ko/common.json';
import enMessages from '../../locales/en/common.json';
import jpMessages from '../../locales/jp/common.json';

interface RootLayoutProps{
  children:ReactNode;
  params: { locale: 'ko' | 'en' | 'jp' }; // 다국어 설정
}

const messagesMap = {
  ko: koMessages,
  en: enMessages,
  jp: jpMessages
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params
}: RootLayoutProps) {
  const messages = messagesMap[params.locale] || koMessages;

  return (
    <html lang={params.locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}> {/* 다국어 설정 */}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
